language: python
python:
  - "3.3"
  - "3.2"
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: python setup.py install
# # command to run tests, e.g. python setup.py test
script:  python test.py
